/** ----------------------------------------------------------------------------------  *
 * Modifications.                                                                       *
 * -------------                                                                        *
 * Ver.No    Date        Author  	    PCR No.          Description of change          *
 * ------ ---------- ---------------- ----------  --------------------------------------*
 * V00    13/10/2016   Siva Prasad														*
 * 					  Prachuri/Alok    PCR012146		 initial version				*
 *                     (X087050)                                                        *
 ****************************************************************************************
 * **********************************************************************
 *  Date        Author    PCR No.          Description of change        *
 ************ ********  **********  *************************************
 * 11/06/2018  X087924   PCR018233  Exe. Service Employee Addition		*
 * 									changes								*
 * 07/31/2018  X087924   PCR018422	Pass Down Log and attachments events*
 * 11/19/2019  Vimal 	 PCR020942	 KA Project changes 				* 
 * 			   Pandu 													*
 * 09/22/2020  X0108356  PCR031702	IBase Implementation				*
 ************************************************************************/
 
jQuery.sap.declare("serviceCaseCreation.util.EventTriggers");

serviceCaseCreation.util.EventTriggers = {

	/*Events for all service case read*/
	TRIGGER_SERVICE_CASES_READ: "TRIGGER_SERVICE_CASES_READ",
	SERVICE_CASES_READ_SUCCESS: "SERVICE_CASES_READ_SUCCESS",
	SERVICE_CASES_READ_FAIL: "SERVICE_CASES_READ_FAIL",

	/*Events for one service case read*/
	TRIGGER_SERVICE_CASE_READ: "TRIGGER_SERVICE_CASE_READ",
	SERVICE_CASE_READ_SUCCESS: "SERVICE_CASE_READ_SUCCESS",
	SERVICE_CASE_READ_FAIL: "SERVICE_CASE_READ_FAIL",

	TRIGGER_SERVICE_CASES_UPDATE: "TRIGGER_SERVICE_CASES_UPDATE",
	SERVICE_CASES_UPDATE_SUCCESS: "SERVICE_CASES_UPDATE_SUCCESS",
	SERVICE_CASES_UPDATE_FAIL: "SERVICE_CASES_UPDATE_FAIL",

	TRIGGER_SERVICE_CASES_SEARCH_READ: "TRIGGER_SERVICE_CASES_SEARCH_READ",
	SERVICE_CASES_SEARCH_SUCCESS: "SERVICE_CASES_SEARCH_SUCCESS",
	SERVICE_CASES_SEARCH_FAIL: "SERVICE_CASES_SEARCH_FAIL",

	TRIGGER_LABOR_LIST_READ: "TRIGGER_LABOR_LIST_READ",
	LABOR_LIST_READ_SUCCESS: "LABOR_LIST_READ_SUCCESS",
	LABOR_LIST_READ_FAIL: "LABOR_LIST_READ_FAIL",

	TRIGGER_CUSTOMER_TOOLID_READ: "TRIGGER_CUSTOMER_TOOLID_READ",
	CUSTOMER_TOOLID_READ_SUCCESS: "CUSTOMER_TOOLID_READ_SUCCESS",
	CUSTOMER_TOOLID_READ_FAIL: "CUSTOMER_TOOLID_READ_FAIL",

	TRIGGER_CASE_CREATION_USER_HELP_READ: "TRIGGER_CASE_CREATION_USER_HELP_READ",
	CASE_CREATION_USER_HELP_SUCCESS: "CASE_CREATION_USER_HELP_SUCCESS",
	CASE_CREATION_USER_HELP_FAIL: "CASE_CREATION_USER_HELP_FAIL",

	TIER_LIST_READ_SUCCESS: "TIER_LIST_READ_SUCCESS",
	TIER_LIST_READ_FAIL: "TIER_LIST_READ_FAIL",
	TRIGGER_TIER_LIST_READ: "TRIGGER_TIER_LIST_READ",

	/*start of PCR018233++ changes*/
	
	TRIGGER_ESE_READ: "TRIGGER_ESE_READ",
	ESE_READ_SUCCESS: "ESE_READ_SUCCESS",
	ESE_READ_FAIL: "ESE_READ_FAIL",
	
	/*end of PCR018233++ changes*/

	/*Start of PCR018422++ changes
	Pass Down Log Read and attachments event triggers*/

	TRIGGER_PSDN_LOG_READ: "TRIGGER_PSDN_LOG_READ",
	PSDN_LOG_READ_SUCCESS: "PSDN_LOG_READ_SUCCESS",
	PSDN_LOG_READ_FAIL: "PSDN_LOG_READ_FAIL",

	ATTACHMENTS_READ_SUCCESS: "ATTACHMENTS_READ_SUCCESS",
	ATTACHMENTS_READ_FAIL: "ATTACHMENTS_READ_FAIL",
	TRIGGER_ATTACHMENTS_READ: "TRIGGER_ATTACHMENTS_READ",

	TRIGGER_PASSDOWNLOG_CREATE: "TRIGGER_PASSDOWNLOG_CREATE",
	PASSDOWNLOG_CREATE_SUCCESS: "PASSDOWNLOG_CREATE_SUCCESS",
	PASSDOWNLOG_CREATE_FAIL: "PASSDOWNLOG_CREATE_FAIL",

	/*End of PCR018422++ changes*/
	
	/*Begin of PCR020942++ changes*/
	
	ASSEM_READ_SUCCESS: "ASSEM_READ_SUCCESS",
	ASSEM_READ_FAIL: "ASSEM_READ_FAIL",
	TRIGGER_ASSEM_READ: "TRIGGER_ASSEM_READ",
	
	/*End of PCR020942++ changes*/
	
	/*Begin of IBase PCR031702++ changes*/
		
	TRIGGER_IBASE_CUSTTOOLID_UPDATE: "TRIGGER_IBASE_CUSTTOOLID_UPDATE",
	IBASE_CUSTTOOLID_UPDATE_SUCCESS: "IBASE_CUSTTOOLID_UPDATE_SUCCESS",
	IBASE_CUSTTOOLID_UPDATE_FAIL: "IBASE_CUSTTOOLID_UPDATE_FAIL",
	
	TRIGGER_IBASE_ASSEMBLYPOSITION_READ:"TRIGGER_IBASE_ASSEMBLYPOSITION_READ",
	IBASE_ASSEMBLYPOSITION_READ_SUCCESS:"IBASE_ASSEMBLYPOSITION_READ_SUCCESS",
	IBASE_ASSEMBLYPOSITION_READ_FAIL:"IBASE_ASSEMBLYPOSITION_READ_FAIL",
		
	TRIGGER_IBASE_POSITION_UPDATE:"TRIGGER_IBASE_POSITION_UPDATE",
	IBASE_POSITION_UPDATE_SUCCESS:"IBASE_POSITION_UPDATE_SUCCESS",
	IBASE_POSITION_UPDATE_FAIL:"IBASE_POSITION_UPDATE_FAIL",
	
	TRIGGER_IBASE_GOTCODE_READ:"TRIGGER_IBASE_GOTCODE_READ",
	IBASE_GOTCODE_READ_SUCCESS:"IBASE_GOTCODE_READ_SUCCESS",
	IBASE_GOTCODE_READ_FAIL:"IBASE_GOTCODE_READ_FAIL",
	
	TRIGGER_IBASE_VALID_READ:"TRIGGER_IBASE_VALID_READ",
	IBASE_VALID_READ_SUCCESS:"IBASE_VALID_READ_SUCCESS",
	IBASE_VALID_READ_FAIL:"IBASE_VALID_READ_FAIL",
	
	/*End of IBase PCR031702++ changes*/
			
}